name: Run playwright test

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run super-lint
        uses: github/super-linter@v5

  run-test:
    name: Run playwright test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run test
        run: npm run test

env:
  DEFAULT_BRANCH: main
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}