name: Run playwright test

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  run-test:
    name: Run playwright test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run test
        run: pnpm test

env:
  DEFAULT_BRANCH: main
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
  AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
  AUTH_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  AUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}